# Epic 3: Data Pre-processing
## Importing Required Libraries

In [47]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

## Loading the Dataset

In [48]:
data = pd.read_csv("../dataset/loan_prediction.csv")
data.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

#Understanding the Dataset Structure

In [49]:
#Display the first five rows
data.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [50]:
#Display the last five rows
data.tail()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [51]:
#Display the shape of the dataset
data.shape

(614, 13)

In [52]:
#Display dataset information
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    str
 1   Gender             601 non-null    str
 2   Married            611 non-null    str
 3   Dependents         599 non-null    str
 4   Education          614 non-null    str
 5   Self_Employed      582 non-null    str
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    str
 12  Loan_Status        614 non-null    str
dtypes: float64(4), int64(1), str(8)
memory usage: 62.5 KB

In [53]:
#Display summary statistics
data.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

## Handling Categorical Values
Inspect dataset

    ↓

Check missing values

    ↓

Handle missing values

    ↓

Encode categorical values

In [54]:
data.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='str')

In [55]:
data.select_dtypes(include='object').head()

C:\Users\BHARATH\AppData\Local\Temp\ipykernel_19100\4181397192.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  data.select_dtypes(include='object').head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,Urban,Y
4,LP001008,Male,No,0,Graduate,No,Urban,Y

In [56]:
import jupyterthemes as jt

## Checking and Handling Missing Values

In [57]:
# Check the number of missing values in each column
data.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [58]:
# Fill missing values in Gender with the mode
data['Gender'] = data['Gender'].fillna(data['Gender'].mode()[0])
# Fill missing values in Married with the mode
data['Married'] = data['Married'].fillna(data['Married'].mode()[0])
# Replace '+' in Dependents before filling missing values
data['Dependents'] = data['Dependents'].str.replace('+', '', regex=False)
# Fill missing values in Dependents with the mode
data['Dependents'] = data['Dependents'].fillna(data['Dependents'].mode()[0])
# Fill missing values in Self_Employed with the mode
data['Self_Employed']=data['Self_Employed'].fillna(data['Self_Employed'].mode()[0])
data['LoanAmount'] = data['LoanAmount'].fillna(data['LoanAmount'].mean())
data['Loan_Amount_Term'] = data['Loan_Amount_Term'].fillna(data['Loan_Amount_Term'].mean())
data['Credit_History'] = data['Credit_History'].fillna(data['Credit_History'].mode()[0])

In [59]:
# Check whether any missing values remain
data.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

## Encoding Categorical Variables

In [60]:
data['Gender']=data['Gender'].map({'Female':1,'Male':0})
data['Property_Area']=data['Property_Area'].map({'Urban':2,'Semiurban':1,'Rural':0})
data['Married']=data['Married'].map({'Yes':1,'No':0})
data['Education']=data['Education'].map({'Graduate':1,'Not Graduate':0})
data['Loan_Status']=data['Loan_Status'].map({'Y':1,'N':0})
data['Dependents'] = data['Dependents'].astype(int)
data['Self_Employed'] = data['Self_Employed'].map({'Yes':1,'No':0})
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    str
 1   Gender             614 non-null    int64
 2   Married            614 non-null    int64
 3   Dependents         614 non-null    int64
 4   Education          614 non-null    int64
 5   Self_Employed      614 non-null    int64
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         614 non-null    float64
 9   Loan_Amount_Term   614 non-null    float64
 10  Credit_History     614 non-null    float64
 11  Property_Area      614 non-null    int64
 12  Loan_Status        614 non-null    int64
dtypes: float64(4), int64(8), str(1)
memory usage: 62.5 KB

## Dataset Information After Pre-processing

In [61]:
# Display dataset information after handling missing values
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    str
 1   Gender             614 non-null    int64
 2   Married            614 non-null    int64
 3   Dependents         614 non-null    int64
 4   Education          614 non-null    int64
 5   Self_Employed      614 non-null    int64
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         614 non-null    float64
 9   Loan_Amount_Term   614 non-null    float64
 10  Credit_History     614 non-null    float64
 11  Property_Area      614 non-null    int64
 12  Loan_Status        614 non-null    int64
dtypes: float64(4), int64(8), str(1)
memory usage: 62.5 KB

In [62]:
data[
    [
        'Gender',
        'Married',
        'Dependents',
        'Education',
        'Self_Employed',
        'Property_Area',
        'Loan_Status'
    ]
].head()

,Gender,Married,Dependents,Education,Self_Employed,Property_Area,Loan_Status
0,0,0,0,1,0,2,1
1,0,1,1,1,0,0,0
2,0,1,0,1,1,2,1
3,0,1,0,0,0,2,1
4,0,0,0,1,0,2,1

## Converting Data Types
use this 
# Convert integer-like columns to int64
columns_to_convert = [
    'Gender',
    'Married',
    'Dependents',
    'Education',
    'Self_Employed',
    'CoapplicantIncome',
    'LoanAmount',
    'Loan_Amount_Term',
    'Credit_History',
    'Property_Area',
    'Loan_Status'
]

data[columns_to_convert] = data[columns_to_convert].astype('int64')

or

In [63]:
# Convert integer-like columns to int64
columns_to_convert = [
    'Gender',
    'Married',
    'Dependents',
    'Education',
    'Self_Employed',
    'CoapplicantIncome',
    'LoanAmount',
    'Loan_Amount_Term',
    'Credit_History',
    'Property_Area',
    'Loan_Status'
]

data[columns_to_convert] = data[columns_to_convert].astype('int64')
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    str
 1   Gender             614 non-null    int64
 2   Married            614 non-null    int64
 3   Dependents         614 non-null    int64
 4   Education          614 non-null    int64
 5   Self_Employed      614 non-null    int64
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    int64
 8   LoanAmount         614 non-null    int64
 9   Loan_Amount_Term   614 non-null    int64
 10  Credit_History     614 non-null    int64
 11  Property_Area      614 non-null    int64
 12  Loan_Status        614 non-null    int64
dtypes: int64(12), str(1)
memory usage: 62.5 KB

## Verifying the Preprocessed Dataset

In [64]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    str
 1   Gender             614 non-null    int64
 2   Married            614 non-null    int64
 3   Dependents         614 non-null    int64
 4   Education          614 non-null    int64
 5   Self_Employed      614 non-null    int64
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    int64
 8   LoanAmount         614 non-null    int64
 9   Loan_Amount_Term   614 non-null    int64
 10  Credit_History     614 non-null    int64
 11  Property_Area      614 non-null    int64
 12  Loan_Status        614 non-null    int64
dtypes: int64(12), str(1)
memory usage: 62.5 KB

In [65]:
data.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [66]:
data.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,0,0,0,1,0,5849,0,146,360,1,2,1
1,LP001003,0,1,1,1,0,4583,1508,128,360,1,0,0
2,LP001005,0,1,0,1,1,3000,0,66,360,1,2,1
3,LP001006,0,1,0,0,0,2583,2358,120,360,1,2,1
4,LP001008,0,0,0,1,0,6000,0,141,360,1,2,1

## Separating Features and Target Variable

In [67]:
# Remove Loan_ID because it is only an identifier
data = data.drop('Loan_ID', axis=1)

In [68]:
# Separate independent variables and target variable
X = data.drop('Loan_Status', axis=1)
y = data['Loan_Status']

In [69]:
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

Shape of X: (614, 11)
Shape of y: (614,)

## Splitting the Dataset into Training and Testing Sets

In [70]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.33,
    random_state=42,
    stratify=y
)

In [71]:
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (411, 11)
X_test shape: (203, 11)
y_train shape: (411,)
y_test shape: (203,)

## Scaling the Features

In [72]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [73]:
X_train_scaled = pd.DataFrame(
    X_train_scaled,
    columns=X_train.columns,
    index=X_train.index
)

X_test_scaled = pd.DataFrame(
    X_test_scaled,
    columns=X_test.columns,
    index=X_test.index
)

## Balancing the Training Dataset Using SMOTE

In [74]:
# Check the class distribution before SMOTE
y_train.value_counts()

Loan_Status
1    282
0    129
Name: count, dtype: int64

In [75]:
from imblearn.over_sampling import SMOTE

In [76]:
smote = SMOTE(random_state=42)

X_train_balanced, y_train_balanced = smote.fit_resample(
    X_train_scaled,
    y_train
)

In [77]:
print("Before SMOTE:")
print(y_train.value_counts())

print("\nAfter SMOTE:")
print(y_train_balanced.value_counts())

Before SMOTE:
Loan_Status
1    282
0    129
Name: count, dtype: int64

After SMOTE:
Loan_Status
1    282
0    282
Name: count, dtype: int64

In [78]:
print("X_train_balanced shape:", X_train_balanced.shape)
print("y_train_balanced shape:", y_train_balanced.shape)
print("X_test shape:", X_test_scaled.shape)
print("y_test shape:", y_test.shape)

X_train_balanced shape: (564, 11)
y_train_balanced shape: (564,)
X_test shape: (203, 11)
y_test shape: (203,)

In [79]:
X_train_balanced.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,2.265906,-1.414214,0.239093,0.525735,-0.397173,-0.411309,-0.012892,-0.668365,0.309011,0.384766,1.226132
1,-0.441325,-1.414214,2.224287,0.525735,-0.397173,0.503095,-0.565686,0.392461,0.309011,0.384766,-1.299884
2,2.265906,-1.414214,0.239093,0.525735,-0.397173,-0.314651,-0.565686,-0.422700,0.309011,0.384766,-0.036876
3,-0.441325,0.707107,1.231690,0.525735,-0.397173,0.079106,1.437838,0.425960,-2.536478,0.384766,-0.036876
4,2.265906,0.707107,1.231690,0.525735,-0.397173,-0.629045,0.100856,0.191462,0.309011,0.384766,1.226132

In [80]:
pd.DataFrame(X_train_balanced, columns=X.columns).head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,2.265906,-1.414214,0.239093,0.525735,-0.397173,-0.411309,-0.012892,-0.668365,0.309011,0.384766,1.226132
1,-0.441325,-1.414214,2.224287,0.525735,-0.397173,0.503095,-0.565686,0.392461,0.309011,0.384766,-1.299884
2,2.265906,-1.414214,0.239093,0.525735,-0.397173,-0.314651,-0.565686,-0.422700,0.309011,0.384766,-0.036876
3,-0.441325,0.707107,1.231690,0.525735,-0.397173,0.079106,1.437838,0.425960,-2.536478,0.384766,-0.036876
4,2.265906,0.707107,1.231690,0.525735,-0.397173,-0.629045,0.100856,0.191462,0.309011,0.384766,1.226132

In [81]:
import os
import joblib

os.makedirs("../artifacts", exist_ok=True)
joblib.dump(scaler, "../artifacts/scaler.pkl")
joblib.dump(X_train_balanced, "../artifacts/X_train_balanced.pkl")
joblib.dump(X_test_scaled, "../artifacts/X_test_scaled.pkl")
joblib.dump(y_train_balanced, "../artifacts/y_train_balanced.pkl")
joblib.dump(y_test, "../artifacts/y_test.pkl")
data.to_csv("../artifacts/cleaned_dataset.csv", index=False)
print("Processed training and testing data saved successfully.")

Processed training and testing data saved successfully.

# Epic 3 Completed Successfully

The dataset has been successfully preprocessed by:

- Handling missing values
- Encoding categorical variables
- Converting data types
- Splitting the dataset into training and testing sets
- Scaling the feature set
- Balancing the training data using SMOTE

The processed dataset is now ready for machine learning model training.