# Epic 4: Model Building

In [102]:
import joblib
import pandas as pd
import pickle

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

from sklearn.model_selection import cross_val_score


# Loading the processed data

In [103]:
X_train_balanced = joblib.load("../artifacts/X_train_balanced.pkl")
X_test_scaled = joblib.load("../artifacts/X_test_scaled.pkl")
y_train_balanced = joblib.load("../artifacts/y_train_balanced.pkl")
y_test = joblib.load("../artifacts/y_test.pkl")
scaler=joblib.load("../artifacts/scaler.pkl")
print("Processed data loaded successfully.")

Processed data loaded successfully.

In [104]:
print("X_train_balanced:", X_train_balanced.shape)
print("X_test_scaled:", X_test_scaled.shape)
print("y_train_balanced:", y_train_balanced.shape)
print("y_test:", y_test.shape)

X_train_balanced: (564, 11)
X_test_scaled: (203, 11)
y_train_balanced: (564,)
y_test: (203,)

## Model Evaluation Function

A reusable function is created to train, evaluate, and compare machine learning models. The function performs the following tasks:

- Trains the model using the training dataset.
- Predicts the output for both training and testing datasets.
- Calculates training and testing accuracy.
- Displays the confusion matrix.
- Displays the classification report.
- Returns the trained model along with its accuracy scores for further comparison.

In [105]:
# Function to train, evaluate, and display model performance
def evaluate_model(model_name, model, X_train, y_train, X_test, y_test):

    # Train the model using the training data
    model.fit(X_train, y_train)

    # Make predictions on both training and testing datasets
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # Calculate training and testing accuracy
    train_accuracy = accuracy_score(y_train, y_train_pred)
    test_accuracy = accuracy_score(y_test, y_test_pred)

    # Display model performance
    print(f"{model_name} Results")
    print("-" * 50)

    print(f"Training Accuracy: {train_accuracy:.4f}")
    print(f"Testing Accuracy : {test_accuracy:.4f}")

    # Display the confusion matrix
    print("\nConfusion Matrix:")
    print(confusion_matrix(y_test, y_test_pred))

    # Display the classification report
    print("\nClassification Report:")
    print(classification_report(y_test, y_test_pred))

    # Return the trained model and accuracy scores
    return model, train_accuracy, test_accuracy

## Decision Tree Model

The Decision Tree model is trained using the balanced training dataset. After training, the model predicts the loan approval status for both the training and testing datasets. The model's performance is evaluated using training accuracy, testing accuracy, a confusion matrix, and a classification report.

In [106]:
# Initialize the Decision Tree classifier
decision_tree_model = DecisionTreeClassifier(random_state=42)

# Train and evaluate the Decision Tree model
decision_tree_model, dt_train_accuracy, dt_test_accuracy = evaluate_model(
    model_name="Decision Tree",
    model=decision_tree_model,
    X_train=X_train_balanced,
    y_train=y_train_balanced,
    X_test=X_test_scaled,
    y_test=y_test
)

Decision Tree Results
--------------------------------------------------
Training Accuracy: 1.0000
Testing Accuracy : 0.7635

Confusion Matrix:
[[ 43  20]
 [ 28 112]]

Classification Report:
              precision    recall  f1-score   support

           0       0.61      0.68      0.64        63
           1       0.85      0.80      0.82       140

    accuracy                           0.76       203
   macro avg       0.73      0.74      0.73       203
weighted avg       0.77      0.76      0.77       203

## Random Forest Model

The Random Forest model combines predictions from multiple decision trees to improve accuracy and reduce overfitting. It is trained using the balanced training dataset and evaluated using training accuracy, testing accuracy, a confusion matrix, and a classification report.

In [107]:
# Initialize the Random Forest classifier with 100 decision trees
random_forest_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

# Train and evaluate the Random Forest model
random_forest_model, rf_train_accuracy, rf_test_accuracy = evaluate_model(
    model_name="Random Forest",
    model=random_forest_model,
    X_train=X_train_balanced,
    y_train=y_train_balanced,
    X_test=X_test_scaled,
    y_test=y_test
)

Random Forest Results
--------------------------------------------------
Training Accuracy: 1.0000
Testing Accuracy : 0.7783

Confusion Matrix:
[[ 37  26]
 [ 19 121]]

Classification Report:
              precision    recall  f1-score   support

           0       0.66      0.59      0.62        63
           1       0.82      0.86      0.84       140

    accuracy                           0.78       203
   macro avg       0.74      0.73      0.73       203
weighted avg       0.77      0.78      0.77       203

## K-Nearest Neighbors (KNN) Model

The K-Nearest Neighbors model classifies a loan application based on the classes of its nearest data points. Since KNN relies on distance calculations, the scaled training and testing data are used. The model is evaluated using training accuracy, testing accuracy, a confusion matrix, and a classification report.

In [108]:
# Initialize the K-Nearest Neighbors classifier
# n_neighbors=5 means the model considers the 5 nearest data points
knn_model = KNeighborsClassifier(n_neighbors=5)

# Train and evaluate the KNN model
knn_model, knn_train_accuracy, knn_test_accuracy = evaluate_model(
    model_name="K-Nearest Neighbors",
    model=knn_model,
    X_train=X_train_balanced,
    y_train=y_train_balanced,
    X_test=X_test_scaled,
    y_test=y_test
)

K-Nearest Neighbors Results
--------------------------------------------------
Training Accuracy: 0.8422
Testing Accuracy : 0.7438

Confusion Matrix:
[[ 41  22]
 [ 30 110]]

Classification Report:
              precision    recall  f1-score   support

           0       0.58      0.65      0.61        63
           1       0.83      0.79      0.81       140

    accuracy                           0.74       203
   macro avg       0.71      0.72      0.71       203
weighted avg       0.75      0.74      0.75       203

## Gradient Boosting Model

The Gradient Boosting model builds multiple weak decision trees sequentially. Each new tree attempts to correct the errors made by the previous trees. The model is trained using the balanced training dataset and evaluated using training accuracy, testing accuracy, a confusion matrix, and a classification report.

> Note: The project material refers to this section as XGBoost, but the implementation uses `GradientBoostingClassifier` from scikit-learn.

In [109]:
# Initialize the Gradient Boosting classifier
gradient_boosting_model = GradientBoostingClassifier(
    random_state=42
)

# Train and evaluate the Gradient Boosting model
gradient_boosting_model, gb_train_accuracy, gb_test_accuracy = evaluate_model(
    model_name="Gradient Boosting",
    model=gradient_boosting_model,
    X_train=X_train_balanced,
    y_train=y_train_balanced,
    X_test=X_test_scaled,
    y_test=y_test
)

Gradient Boosting Results
--------------------------------------------------
Training Accuracy: 0.9273
Testing Accuracy : 0.7685

Confusion Matrix:
[[ 37  26]
 [ 21 119]]

Classification Report:
              precision    recall  f1-score   support

           0       0.64      0.59      0.61        63
           1       0.82      0.85      0.84       140

    accuracy                           0.77       203
   macro avg       0.73      0.72      0.72       203
weighted avg       0.76      0.77      0.77       203

## Model Performance Comparison

The performance of all trained machine learning models is compared using their training and testing accuracies. This comparison helps identify the model that generalizes best on unseen data and assists in selecting the most suitable model for deployment.

In [110]:
# Create a DataFrame to compare the performance of all models
model_results = pd.DataFrame({
    "Model": [
        "Decision Tree",
        "Random Forest",
        "K-Nearest Neighbors",
        "Gradient Boosting"
    ],
    "Training Accuracy": [
        dt_train_accuracy,
        rf_train_accuracy,
        knn_train_accuracy,
        gb_train_accuracy
    ],
    "Testing Accuracy": [
        dt_test_accuracy,
        rf_test_accuracy,
        knn_test_accuracy,
        gb_test_accuracy
    ]
})

# Display the comparison table
model_results

                 Model  Training Accuracy  Testing Accuracy
0        Decision Tree           1.000000          0.763547
1        Random Forest           1.000000          0.778325
2  K-Nearest Neighbors           0.842199          0.743842
3    Gradient Boosting           0.927305          0.768473

In [111]:
# Sort the models based on testing accuracy
model_results = model_results.sort_values(
    by="Testing Accuracy",
    ascending=False
)

# Display the sorted comparison
model_results

                 Model  Training Accuracy  Testing Accuracy
1        Random Forest           1.000000          0.778325
3    Gradient Boosting           0.927305          0.768473
0        Decision Tree           1.000000          0.763547
2  K-Nearest Neighbors           0.842199          0.743842

## Cross-Validation

Cross-validation is used to evaluate the consistency and reliability of a machine learning model. In 5-fold cross-validation, the training dataset is divided into five equal subsets. The model is trained and validated five times, using a different subset for validation during each iteration. The average accuracy across all folds provides a more reliable estimate of model performance.

In [112]:
# Store all machine learning models in a dictionary
models = {
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(
        n_estimators=100,
        random_state=42
    ),
    "K-Nearest Neighbors": KNeighborsClassifier(n_neighbors=5),
    "Gradient Boosting": GradientBoostingClassifier(
        random_state=42
    )
}

In [113]:
# Create an empty dictionary to store cross-validation results
cross_validation_results = {}

# Perform 5-fold cross-validation for each model
for model_name, model in models.items():

    scores = cross_val_score(
        model,
        X_train_balanced,
        y_train_balanced,
        cv=5,
        scoring="accuracy"
    )

    # Store the average cross-validation accuracy
    cross_validation_results[model_name] = scores.mean()

    # Display the results
    print(f"{model_name}")
    print(f"Cross-Validation Scores: {scores}")
    print(f"Average Accuracy: {scores.mean():.4f}")
    print(f"Standard Deviation: {scores.std():.4f}")
    print("-" * 50)

Decision Tree
Cross-Validation Scores: [0.69026549 0.71681416 0.76106195 0.74336283 0.72321429]
Average Accuracy: 0.7269
Standard Deviation: 0.0241
--------------------------------------------------
Random Forest
Cross-Validation Scores: [0.75221239 0.74336283 0.83185841 0.84070796 0.88392857]
Average Accuracy: 0.8104
Standard Deviation: 0.0542
--------------------------------------------------
K-Nearest Neighbors
Cross-Validation Scores: [0.76106195 0.7079646  0.72566372 0.74336283 0.75892857]
Average Accuracy: 0.7394
Standard Deviation: 0.0202
--------------------------------------------------
Gradient Boosting
Cross-Validation Scores: [0.72566372 0.72566372 0.78761062 0.83185841 0.83928571]
Average Accuracy: 0.7820
Standard Deviation: 0.0493
--------------------------------------------------

## Updated Model Comparison

The average cross-validation accuracy is added to the model comparison table to provide a more comprehensive evaluation. This helps identify the model that performs consistently across different subsets of the training data.

In [114]:
# Add cross-validation accuracy to the comparison table
# Add the correct cross-validation accuracy by matching each model name
model_results["Cross Validation Accuracy"] = model_results["Model"].map(
    cross_validation_results
)

# Display the updated comparison table
model_results

,Model,Training Accuracy,Testing Accuracy,Cross Validation Accuracy
1,Random Forest,1.000000,0.778325,0.810414
3,Gradient Boosting,0.927305,0.768473,0.782016
0,Decision Tree,1.000000,0.763547,0.726944
2,K-Nearest Neighbors,0.842199,0.743842,0.739396

In [115]:
# Sort models by cross-validation accuracy
model_results = model_results.sort_values(
    by="Cross Validation Accuracy",
    ascending=False
).reset_index(drop=True)

# Display the final comparison table
model_results

,Model,Training Accuracy,Testing Accuracy,Cross Validation Accuracy
0,Random Forest,1.000000,0.778325,0.810414
1,Gradient Boosting,0.927305,0.768473,0.782016
2,K-Nearest Neighbors,0.842199,0.743842,0.739396
3,Decision Tree,1.000000,0.763547,0.726944

## Best Model Selection

The models are compared using testing accuracy and 5-fold cross-validation accuracy. Cross-validation is used to evaluate performance consistency across different data splits. The model with the strongest cross-validation performance, supported by its testing accuracy, is selected for deployment.

In [116]:
# Store the trained models in a dictionary
trained_models = {
    "Decision Tree": decision_tree_model,
    "Random Forest": random_forest_model,
    "K-Nearest Neighbors": knn_model,
    "Gradient Boosting": gradient_boosting_model
}

# Store the testing accuracies
test_accuracies = {
    "Decision Tree": dt_test_accuracy,
    "Random Forest": rf_test_accuracy,
    "K-Nearest Neighbors": knn_test_accuracy,
    "Gradient Boosting": gb_test_accuracy
}

# Select the model with the highest average cross-validation accuracy
best_model_name = max(
    cross_validation_results,
    key=cross_validation_results.get
)

# Retrieve the selected trained model
best_model = trained_models[best_model_name]

# Retrieve its testing and cross-validation accuracies
best_test_accuracy = model_results.loc[
    model_results["Model"] == best_model_name,
    "Testing Accuracy"
].iloc[0]

best_cv_accuracy = cross_validation_results[best_model_name]

# Display the selected model and its performance
print("Best Model:", best_model_name)
print(f"Testing Accuracy: {best_test_accuracy:.4f}")
print(f"Cross-Validation Accuracy: {best_cv_accuracy:.4f}")

# # Identify the best model based on testing accuracy
# best_model_name = max(cross_validation_results, key=cross_validation_results.get)
# best_model = trained_models[best_model_name]

# # Display the best model details
# print("Best Model:", best_model_name)
# print("Testing Accuracy:", test_accuracies[best_model_name])

Best Model: Random Forest
Testing Accuracy: 0.7783
Cross-Validation Accuracy: 0.8104

## Saving the Best Model

The selected model is saved as a `.pkl` file using the `pickle` library. This serialized model can later be loaded into the Flask application to make loan approval predictions without retraining the model.

In [117]:
# Import the os module
import os

# Create the models directory if it does not already exist
os.makedirs("../models", exist_ok=True)

# Define the model file path
model_path = "../models/best_loan_model.pkl"

# Save the best model
with open(model_path, "wb") as file:
    pickle.dump(best_model, file)

print("Best model saved successfully!")
print("Model Path:", model_path)

Best model saved successfully!
Model Path: ../models/best_loan_model.pkl

## Model Verification

The saved model is loaded back into memory to verify that it has been stored correctly. Its prediction accuracy is then evaluated using the testing dataset.

In [118]:
# Load the saved model
with open("../models/best_loan_model.pkl", "rb") as file:
    loaded_model = pickle.load(file)

# Make predictions using the loaded model
loaded_predictions = loaded_model.predict(X_test_scaled)

# Calculate the loaded model's testing accuracy
loaded_model_accuracy = accuracy_score(y_test, loaded_predictions)

print("Loaded Model:", type(loaded_model).__name__)
print(f"Loaded Model Accuracy: {loaded_model_accuracy:.4f}")
print(
    "Model verification successful:",
    loaded_model_accuracy == best_test_accuracy
)

Loaded Model: RandomForestClassifier
Loaded Model Accuracy: 0.7783
Model verification successful: True

## Saving the Feature Scaler

The feature scaler used during preprocessing is saved so that the same scaling transformation can be applied to new user inputs during prediction.

In [119]:
import joblib

# Save the scaler
joblib.dump(scaler, "../models/scaler.pkl")

print("Scaler saved successfully!")

Scaler saved successfully!

# Conclusion

In this epic, four machine learning classification models—Decision Tree, Random Forest, K-Nearest Neighbors (KNN), and Gradient Boosting—were successfully trained and evaluated using the preprocessed loan prediction dataset.

The performance of each model was assessed using training accuracy, testing accuracy, confusion matrices, classification reports, and 5-fold cross-validation. Cross-validation was performed to verify the consistency of each model across different data splits and to ensure reliable performance.

After comparing the evaluation metrics, the **Random Forest** model demonstrated the best overall performance for this implementation. The selected model was then serialized and saved as a `.pkl` file using the `pickle` library, enabling it to be integrated into the Flask web application for real-time loan approval prediction. The saved model was also reloaded and verified to ensure successful serialization and deployment readiness.

This completes the model building phase and prepares the project for the final deployment and application integration stage.